/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.examples;

import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void checkTestCaseOne() throws FileNotFoundException {
        String[] input = creatInputForTest("test_case_1");
        assertTrue(MinimumTrianglePaths.getMinimumSumPatch(input) == 18);
    }

    @Test
    public void checkTestCaseTwo() throws FileNotFoundException {
        String[] input = creatInputForTest("test_case_2");
        assertTrue(MinimumTrianglePaths.getMinimumSumPatch(input) != -1);
    }


    private String[] creatInputForTest(String fileName) throws FileNotFoundException {
        Path testCase = Paths.get("src", "test", "resources", "test_case_1");
        String fileValue = readFile(testCase);
        return fileValue.split("\n");
    }

    private String readFile(Path path) throws FileNotFoundException {
        return new Scanner(path.toFile().getAbsoluteFile())
                .useDelimiter("\\Z")
                .next();
    }
}
